version: '3'
services:
  database:
    image: postgres:latest
    container_name: ecom-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecom-example
